[app]
name = "MoltenMeta"
version = "0.1.0105"
stage = "dev" # dev, alpha, beta, rc, stable
is_default_config = true

[runtime]
python_version = "3.14.2"
profile = "debug"

[database]
db_type = "sqlite"
file_path = "data"
file_name = "moltenmeta.mmdb"

[logging]
level = "info" # debug, info, warning, error, critical
enable_file_logging = true
enable_console = true

[locale]
language = "en"
theme = "blue"
scheme = "dark"