[log]
level = "info"
file_logging = false
enable_console = false

[appearance]
theme = "blue"
scheme = "light"
theme_mode = "system"
enable_auto_dark_mode = true

[locale]
language = "en"

[runtime]
python_version = "3.14"

[database]
db_type = "sqlite"
sqlite_path = "data/db/moltenmeta.mmdb"
database_file = "moltenmeta.mmdb"