[app]
name = "MoltenMeta"
version = "0.1.0105"
stage = "dev" # dev, alpha, beta, rc, stable
is_default_config = true

[runtime]
python_version = "3.14.2"
profile = "debug"

[logging]
level = "info" # info, warning, error
enable_file_logging = true
enable_console = true

[locale]
language = "en"
theme = "default"